name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.10.10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with pytest
        run: |
          python -m pytest Calculator/
